-- HamLog database schema
-- This runs automatically on first Docker container startup.

CREATE TABLE IF NOT EXISTS `Contacts` (
  `QSO_ID` INT AUTO_INCREMENT,
  `QSO_Date` DATETIME NULL,
  `QSO_MTZTime` VARCHAR(12) NULL,
  `QSO_Callsign` VARCHAR(12) NULL,
  `QSO_Frequency` VARCHAR(15) NULL,
  `QSO_Notes` VARCHAR(4096) NULL,
  `QSO_Received` VARCHAR(10) NULL,
  `QSO_Sent` VARCHAR(10) NULL,
  PRIMARY KEY (`QSO_ID`)
);

CREATE TABLE IF NOT EXISTS `POTA_QSOs` (
  `POTA_QSO_ID` INT AUTO_INCREMENT,
  `QSO_ID` INT,
  `POTAPark_ID` VARCHAR(10),
  `QSO_Type` VARCHAR(2),
  PRIMARY KEY (`POTA_QSO_ID`),
  FOREIGN KEY (`QSO_ID`) REFERENCES `Contacts`(`QSO_ID`)
);

CREATE TABLE IF NOT EXISTS `Contests` (
  `CONTEST_ID` INT AUTO_INCREMENT,
  `CONTEST_NAME` VARCHAR(512),
  `CONTEST_DESCRIPTION` VARCHAR(1024),
  `CONTEST_BEGINS_ON_DATE` DATETIME NULL,
  `CONTEST_BEGINS_ON_TIME` DATETIME NULL,
  `CONTEST_ENDS_ON_DATE` DATETIME NULL,
  `CONTEST_ENDS_ON_TIME` DATETIME NULL,
  `CONTEST_EXCHANGE_DATA` VARCHAR(1024) NULL,
  PRIMARY KEY (`CONTEST_ID`)
);

CREATE TABLE IF NOT EXISTS `Contest_QSOs` (
  `CONTEST_QSO_ID` INT AUTO_INCREMENT,
  `QSO_ID` INT,
  `CONTEST_ID` INT,
  `CONTEST_QSO_NUMBER` VARCHAR(10),
  `CONTEST_QSO_EXCHANGE_DATA` VARCHAR(128),
  PRIMARY KEY (`CONTEST_QSO_ID`),
  FOREIGN KEY (`QSO_ID`) REFERENCES `Contacts`(`QSO_ID`),
  FOREIGN KEY (`CONTEST_ID`) REFERENCES `Contests`(`CONTEST_ID`)
);

CREATE TABLE IF NOT EXISTS `ContactInfo` (
  `ContactInfo_ID` INT NOT NULL AUTO_INCREMENT,
  `ContactInfo_Callsign` VARCHAR(10) NOT NULL,
  `ContactInfo_Name` VARCHAR(100) NULL,
  `ContactInfo_Street` VARCHAR(100) NULL,
  `ContactInfo_City` VARCHAR(100) NULL,
  `ContactInfo_usState` VARCHAR(100) NULL,
  `ContactInfo_AddressCountry` VARCHAR(100) NULL,
  `ContactInfo_Latitude` VARCHAR(100) NULL,
  `ContactInfo_Longitude` VARCHAR(100) NULL,
  `ContactInfo_ITUZone` VARCHAR(100) NULL,
  `ContactInfo_GridSquare` VARCHAR(100) NULL,
  `ContactInfo_QTH` VARCHAR(100) NULL,
  `ContactInfo_Country` VARCHAR(100) NULL,
  PRIMARY KEY (`ContactInfo_ID`),
  UNIQUE INDEX `ContactInfo_Callsigh_UNIQUE` (`ContactInfo_Callsign` ASC)
);
